export const icons: Record<string, string> = {
  Python: "/tech-stack/python.svg",
  JavaScript: "/tech-stack/javascript.svg",
  TypeScript: "/tech-stack/typescript.svg",
  "C++": "/tech-stack/cplusplus.svg",
  Dart: "/tech-stack/dart.svg",
  SQL: "/tech-stack/sql.svg",
  HTML: "/tech-stack/html.svg",
  CSS: "/tech-stack/css.svg",
  React: "/tech-stack/react.svg",
  "Next.js": "/tech-stack/next-js.svg",
  Bootstrap: "/tech-stack/bootstrap.svg",
  Tailwind: "/tech-stack/tailwind.svg",
  "Tailwind CSS": "/tech-stack/tailwind.svg",
  "Prism.js": "/tech-stack/prism-js.svg",
  "Node.js": "/tech-stack/node-js.svg",
  Bun: "/tech-stack/bun.svg",
  "Express.js": "/tech-stack/express-js.svg",
  FastAPI: "/tech-stack/fastapi.svg",
  Flask: "/tech-stack/flask.svg",
  WebSockets: "/tech-stack/websockets.svg",
  Pandas: "/tech-stack/pandas.svg",
  NumPy: "/tech-stack/numpy.svg",
  Matplotlib: "/tech-stack/matplotlib.svg",
  Seaborn: "/tech-stack/seaborn.svg",
  "Scikit-learn": "/tech-stack/scikit-learn.svg",
  "OpenAI SDK": "/tech-stack/openai.svg",
  "Gemini API": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Google_Gemini_icon_2025.svg",
  MongoDB: "/tech-stack/mongodb.svg",
  SQLite: "/tech-stack/sqlite.svg",
  PostgreSQL: "/tech-stack/postgresql.svg",
  MySQL: "/tech-stack/mysql.svg",
  Firebase: "/tech-stack/firebase.svg",
  Appwrite: "/tech-stack/appwrite.svg",
  Redis: "/tech-stack/redis.svg",
  NeonDB: "/tech-stack/neondb.svg",
  Drizzle: "/tech-stack/drizzle.svg",
  Flutter: "/tech-stack/flutter.svg",
  Docker: "/tech-stack/docker.svg",
  CLI: "/tech-stack/cli.svg",
  Git: "/tech-stack/git.svg",
  GitHub: "/tech-stack/github.svg",
  Postman: "/tech-stack/postman.svg",
  "VS Code": "/tech-stack/code.svg",
  PyCharm: "/tech-stack/pycharm.svg",
  Linux: "/tech-stack/linux.svg",
  Kubernetes: "/tech-stack/kubernetes.svg",
  Jupyter: "/tech-stack/jupyter.svg",
  BetterAuth: "/tech-stack/betterauth.svg",
  Zod: "/tech-stack/zod-icon.svg",
  Shadcn: "/tech-stack/shadcn-icon.svg",
  Vercel: "/tech-stack/vercel.svg",
};
